version: '2'
services:
  jod:  
    image: processoeletronico/vagrant_super4_jod:${ENVIRONMENT_VERSION}
    container_name: jod

  smtp:
    image: processoeletronico/vagrant_super4_mailcatcher:${ENVIRONMENT_VERSION}
    container_name: smtp
    ports:
      - "1080:1080"

  memcached:
    image: processoeletronico/vagrant_super4_memcached:${ENVIRONMENT_VERSION}
    container_name: memcached
    ports:
      - "11211:11211"

  database:
    image: ${DATABASE_IMAGE}:${ENVIRONMENT_VERSION}
    container_name: ${DATABASE_HOST}
    restart: always
    volumes:
      - ${DATABASE_TYPE}:${DATABASE_DATA_DIR}
      - /var/sei/backup/${DATABASE_HOST}:/backup
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

  solr:
    image: processoeletronico/vagrant_super4_solr:${ENVIRONMENT_VERSION}
    container_name: solr
    ports:
      - "8983:8983"

  httpd:
    image: processoeletronico/vagrant_super4_httpd:${ENVIRONMENT_VERSION}
    container_name: httpd
    restart: always
    ports:
      - "8000:8000"
    depends_on: 
      - database
    volumes:
      - /mnt/sei/src/sei:/opt/sei
      - /mnt/sei/src/sip:/opt/sip
      - /mnt/sei/src/infra:/opt/infra
    environment:
      - LANG=pt_BR.ISO-8859-1
      - XDEBUG_CONFIG="idekey=default client_host=host.docker.internal client_port=9003 discover_client_host=1"
      - XDEBUG_SESSION=default
      - XDEBUG_MODE=debug
      - HOST_URL=http://localhost:8000
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

      - SEI_CHAVE_ACESSO=${SEI_CHAVE_ACESSO}
      - SEI_DATABASE_NAME=${SEI_DATABASE_NAME}
      - SEI_DATABASE_USER=${SEI_DATABASE_USER}
      - SEI_DATABASE_PASSWORD=${SEI_DATABASE_PASSWORD}
      - SEI_DATABASE_USER_SCRIPT=${SEI_DATABASE_USER_SCRIPT}
      - SEI_DATABASE_PASSWORD_SCRIPT=${SEI_DATABASE_PASSWORD_SCRIPT}

      - SIP_CHAVE_ACESSO=${SIP_CHAVE_ACESSO}
      - SIP_DATABASE_NAME=${SIP_DATABASE_NAME}
      - SIP_DATABASE_USER=${SIP_DATABASE_USER}
      - SIP_DATABASE_PASSWORD=${SIP_DATABASE_PASSWORD}
      - SIP_DATABASE_USER_SCRIPT=${SIP_DATABASE_USER_SCRIPT}
      - SIP_DATABASE_PASSWORD_SCRIPT=${SIP_DATABASE_PASSWORD_SCRIPT}
    links:
      - database:${DATABASE_HOST}
      - memcached:memcached
      - solr:solr
      - smtp:smtp
      - jod:jod

volumes:
  MySql:
  Oracle:
  SqlServer:
  PostgreSql:
